### ISSUE TITLE
"rake styles:watch" and "compass watch" returns an error

### ISSUE THREAD

**Issue by DahmaniAdame** [adamstac/sinatra-bootstrap#2]
Fresh install using rvm and bundler. 

$ rake styles:watch
(in /opt/lampp/htdocs/processing.com/sinatra-bootstrap)
LoadError on line ["120"] of /home/####/.rvm/gems/ruby-1.9.2-p290@sinatra-bootstrap/gems/compass-0.11.1/lib/compass/configuration/data.rb: no such file to load -- meyer-reset
Run with --trace to see the full backtrace

$ compass watch
LoadError on line ["36"] of /home/####/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb: no such file to load -- meyer-reset
Run with --trace to see the full backtrace

**Comment by adamstac** [comment]
This should be fixed. Thanks for reporting.
